name: Docker CI Esempio

on: [push, pull_request]

jobs:
  build-and-run:
         runs-on: ubuntu-latest

         steps:
         - name: prima action step 1
           uses: actions/checkout@v3

         - name: prima action step 2
           run: docker build -t my-simple-app.

         - name: prima action step 3
           run: docker run --rm my-simple-app
